package com.px3j.lush.core.ticket;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.springframework.beans.BeanUtils;
import org.springframework.security.core.authority.SimpleGrantedAuthority;

import java.io.Serializable;
import java.util.*;

/**
 * LushTicket allows access to a Lush protected service.  Typically, the ticket will be generated by a service that
 * will create it based on a token (ie: JWT).  Once the ticket is obtained, it can be used to access any Lush
 * protected service.
 */
@ToString
public class LushTicket implements Serializable {
    @Getter
    @Setter
    private String id;
    @Getter
    @Setter
    private String username;
    @Getter
    @Setter
    private String password;
    @Getter
    @Setter
    private Collection<SimpleGrantedAuthority> authorities = new ArrayList<>();

    private final Map<String,Object> extras = new HashMap<>();

    public LushTicket() {
        this.id = null;
        this.username = "unknown";
        this.password = "";
    }

    public LushTicket(String username, String password, Collection<SimpleGrantedAuthority> authorities) {
        this.username = username;
        this.password = password;
        this.authorities = authorities;
    }

    /**
     * Will update this LushTicket with all values from the other ticket.
     *
     * @param other The source to copy values from.
     */
    public void populateFrom( LushTicket other ) {
        BeanUtils.copyProperties( other, this );
    }

    public Map<String, Object> getExtras() {
        return Collections.unmodifiableMap(extras);
    }

    /**
     * Added so that extras are propagated during marshalling/unmarshalling.  It is not recommended to use this method
     * in your code.  Use: #see LushTicket::putExtra
     *
     * @param extras Map of extras to set, note that this will replace any extras that already exist.
     */
    public void setExtras( Map<String,Object> extras ) {
        this.extras.putAll( extras );
    }

    /**
     * Set an 'extra' in this ticket.  Extras are used to carry information that is specific to your usage of Lush
     *
     * @param key The key of the extra.
     * @param value The value of the extra.
     */
    public void putExtra(final String key, final Object value ) {
        this.extras.put( key, value );
    }
}
